package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"os"
	"path"
	"strings"
	"sync"
)

func main() {
	entries, err := os.ReadDir("./sql/queries")
	if err != nil {
		panic(err)
	}

	var wg sync.WaitGroup
	errs := make(chan error, len(entries))
	for _, v := range entries {
		name := v.Name()
		if strings.HasSuffix(name, ".sql") {
			wg.Go(func() {
				if m, err := processFile(name); err != nil {
					errs <- fmt.Errorf("process file: %w", err)
				} else {
					if err = writeTo(name, m); err != nil {
						errs <- fmt.Errorf("write generated file: %w", err)
					}
				}
			})
			// if m, err := processFile(name); err != nil {
			// 	panic(fmt.Errorf("process file: %w", err))
			// } else {
			// 	if err = writeTo(name, m); err != nil {
			// 		panic(fmt.Errorf("write generated file: %w", err))
			// 	}
			// }
		}
	}

	wg.Wait()
}

func sanitizeSql(input string) (string, error) {
	b := bytes.Buffer{}
	beforeWasSpace := false
	for _, c := range input {
		switch c {
		case ' ', '\n', '\t':
			if beforeWasSpace {
				continue
			}
			beforeWasSpace = true
			b.WriteRune(' ')
		case '"':
			beforeWasSpace = false
			b.WriteString("\\\"")
		default:
			beforeWasSpace = false
			b.WriteRune(c)
		}
	}
	buf := b.Bytes()
	for len(buf) > 1 && buf[len(buf)-1] != ';' {
		buf = buf[:len(buf)-1]
	}
	return string(buf), nil
}

func processFile(name string) (map[string]string, error) {
	handle, err := os.Open(path.Join("./sql/queries", name))
	if err != nil {
		return nil, err
	}
	defer handle.Close()

	reader := bufio.NewReader(handle)

	m := make(map[string]string)
	var (
		key   string
		value string
	)
	for {
		lineb, err := reader.ReadBytes('\n')
		if err != nil {
			if err == io.EOF {
				break
			}
			return nil, err
		}

		lineb = lineb[:len(lineb)-1]
		line := string(lineb)

		name, found := strings.CutPrefix(line, "--Generate: ")
		if found {
			if key != "" {
				if value, err = sanitizeSql(value); err != nil {
					return nil, err
				}
				m[key] = value
			}
			key = name
			value = ""
		} else {
			if key == "" {
				continue
			}
			value += line + " "
		}
	}
	if key != "" {
		m[key] = value
	}

	return m, nil
}

func writeTo(name string, m map[string]string) error {
	name, _ = strings.CutSuffix(name, ".sql")

	outPath := path.Join(
		"./internal/repository/",
		fmt.Sprintf("%s_generate.go", name),
	)

	handle, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer handle.Close()

	if _, err = handle.WriteString(
		"// Code generated by govalid; DO NOT EDIT.\n",
	); err != nil {
		return err
	}

	if _, err = handle.WriteString(
		"package repository\n\n",
	); err != nil {
		return err
	}

	for k, v := range m {
		_, err = fmt.Fprintf(handle, "const query_%s_%s = \"%s\"\n\n", name, k, v)
		if err != nil {
			return err
		}
	}

	return nil
}
